name: Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.1
      - name: Generate Environment Variables File for Production
        run: |
          echo "REACT_APP_ENV=$REACT_APP_ENV" >> .env.production
          echo "REACT_APP_TMDB_API_KEY=$REACT_APP_TMDB_API_KEY" >> .env.production
          echo "REACT_APP_IP_ADDRESS=$REACT_APP_IP_ADDRESS" >> .env.production
          echo "REACT_APP_BASE_URL=$REACT_APP_BASE_URL" >> .env.production
          echo "REACT_APP_TMDB_API_URL=$REACT_APP_TMDB_API_URL" >> .env.production
          echo "REACT_APP_TMDB_IMG_URL=$REACT_APP_TMDB_IMG_URL" >> .env.production
          echo "REACT_APP_DEFAULT_LANGUAGE=$REACT_APP_DEFAULT_LANGUAGE" >> .env.production
          echo "REACT_APP_KAKAO_API_KEY=$REACT_APP_KAKAO_API_KEY" >> .env.production
        env:
          REACT_APP_ENV: ${{ secrets.REACT_APP_ENV }}
          REACT_APP_TMDB_API_KEY: ${{ secrets.REACT_APP_TMDB_API_KEY }}
          REACT_APP_IP_ADDRESS: ${{ secrets.REACT_APP_IP_ADDRESS }}
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
          REACT_APP_TMDB_API_URL: ${{ secrets.REACT_APP_TMDB_API_URL }}
          REACT_APP_TMDB_IMG_URL: ${{ secrets.REACT_APP_TMDB_IMG_URL }}
          REACT_APP_DEFAULT_LANGUAGE: ${{ secrets.REACT_APP_DEFAULT_LANGUAGE }}
          REACT_APP_KAKAO_API_KEY: ${{ secrets.REACT_APP_KAKAO_API_KEY }}
      - name: npm install and build
        run: |
          npm install
          export REACT_APP_ENV=production
          npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.WSD4 }}
          publish_dir: ./build
